#!/bin/bash

set -o pipefail

# Current user and group ids
USER_ID=$(id -u)
GROUP_ID=$(id -g)

# Allow override of the user we'll run as. Default to root
PUID="${PUID:-0}"
PGID="${PGID:-0}"

echo "USER_ID: $USER_ID"
echo "GROUP_ID: $GROUP_ID"
echo "PUID: $PUID"
echo "PGID: $PGID"

# Check if we could do any user management
if [ "$USER_ID" != "0" ] ; then
  # Nothing we can do with user management as we're already another user. Just
  # call the wrapper
  echo "Already non-root (${USER_ID}:${GROUP_ID}). No user management possible. Calling wrapper"
  exec /wrapper
  echo "Failed call to wrapper"
  exit 1
fi

# Determine the target group name
if ! TARGET_GROUP=$(getent group "${PGID}" | cut -f 1 -d ':') ; then
  # Can't identify the name for the group, so we'll create one
  echo "Target group doesn't exist. Creating"
  if ! groupadd -g "${PGID}" oxidized ; then
    echo "Failed to add oxidized group"
    exit 1
  fi
else
  echo "Target group already exists"
fi

if ! TARGET_GROUP=$(getent group "${PGID}" | cut -f 1 -d ':') ; then
  echo "Could not resolve $PGID to group name or create new group"
  exit 1
fi

if [ "$TARGET_GROUP" == "" ] ; then
  echo "Empty target group name"
  exit 1
fi
echo "Target Group: $TARGET_GROUP"

# Determine the target user name
if ! TARGET_USER=$(getent passwd "${PUID}" | cut -f 1 -d ':') ; then
  # Can't identify the name for the user, so we'll create one
  echo "Target user doesn't exist. Creating."
  if ! useradd -u "${PUID}" -g "${PGID}" -M -d $HOME oxidized ; then
    echo "Failed to add oxidized user"
    exit 1
  fi
else
  echo "Target user already exists"
fi

if ! TARGET_USER=$(getent passwd "${PUID}" | cut -f 1 -d ':') ; then
  echo "Could not resolve $PUID to group name or create new group"
  exit 1
fi

if [ "$TARGET_USER" == "" ] ; then
  echo "Empty target group name"
  exit 1
fi
echo "Target User: $TARGET_USER"

# Call the wrapper
echo "Running wrapper as ${TARGET_USER}:${TARGET_GROUP}"
exec su -g "${TARGET_GROUP}" -c /wrapper "${TARGET_USER}"
echo "Failed call to wrapper"
exit 1
