#!/bin/bash

OXIDIZED_ROOT="$HOME/.config/oxidized"
SOURCE_CONFIG="$HOME/config"
CONFIG_FILE="$OXIDIZED_ROOT/config"

# Create the oxidized directory
echo "Creating oxidized root: $OXIDIZED_ROOT"
if ! mkdir -p "$OXIDIZED_ROOT" ; then
  echo "Failed to create oxidized directory"
  exit 1
fi

# Copy the source configuration, if present
if [ -f "$SOURCE_CONFIG" ] ; then
  echo "Config found in $SOURCE_CONFIG"
  if ! cp "$SOURCE_CONFIG" "$CONFIG_FILE" ; then
    echo "Failed to copy configuration to $CONFIG_FILE"
    exit 1
  else
    echo "Copied configuration to $CONFIG_FILE"
  fi
else
  echo "Did not find source config in $SOURCE_CONFIG"
fi

# Execute oxidized
exec /usr/local/bin/oxidized

# Could not run oxidized, so exit with failure
echo "Could not run oxidized"
exit 1
