# frozen_string_literal: true

source "https://rubygems.org"

gem "oxidized-web", "0.13.1"
gem "oxidized", "0.29.1"
gem "psych", "3.3.2"
gem "net-ssh", "7.1.0"
gem "net-telnet", "0.2.0"
gem "net-tftp", "0.1.0"
gem "slop", "4.10.1"
